<?php 
/** @var \Core\Utils\Url $url */
$url        = $this->getDI()->get('url'); 
$session    = $this->getDI()->get('session');
$navigation = $this->getDI()->get('navigation');
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= htmlspecialchars($title ?? 'Our Framework') ?></title>
    <link rel="stylesheet" href="<?= $url->get('css/pico.min.css') ?>">
    <style>
        body {margin-top: 150px}
        .pico dialog > article {padding: 50px;}
    </style>
</head>
<body>
    <!-- Content Area -->
    <main class="container">
        <section class="pico">
        <?php foreach($this->messages() as $msg): ?>
            <div class="alert alert-<?= $msg['type'] ?>"><?= $msg['message'] ?></div>
        <?php endforeach; ?>
        <?php echo $this->yield('content'); ?>
        </section>
    </main>

    <script src="<?= $url->get('js/app.js') ?>"></script>
</body>
</html>