<?php
// app/Eav/Config/entities/customer.php

/**
 * Customer Entity Configuration
 * 
 * Establishes customer profile structure with personal information fields,
 * contact details, and relationship attributes.
 */
return [
    'entity_code' => 'customer',
    'entity_label' => 'Customer',
    'entity_table' => 'eav_customer_entity',
    'storage_strategy' => 'eav',
    'enable_cache' => true,
    'cache_ttl' => 3600,

    'attributes' => [
        // Personal Information
        [
            'attribute_code' => 'first_name',
            'attribute_label' => 'First Name',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => true,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'min_length' => 2,
                'max_length' => 255,
            ],
            'sort_order' => 10,
        ],
        [
            'attribute_code' => 'last_name',
            'attribute_label' => 'Last Name',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => true,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'min_length' => 2,
                'max_length' => 255,
            ],
            'sort_order' => 20,
        ],
        [
            'attribute_code' => 'email',
            'attribute_label' => 'Email Address',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => true,
            'is_unique' => true,
            'is_searchable' => true,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'pattern' => '/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/',
                'max_length' => 255,
            ],
            'sort_order' => 30,
        ],
        [
            'attribute_code' => 'date_of_birth',
            'attribute_label' => 'Date of Birth',
            'backend_type' => 'datetime',
            'frontend_type' => 'date',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'sort_order' => 40,
        ],
        [
            'attribute_code' => 'gender',
            'attribute_label' => 'Gender',
            'backend_type' => 'int',
            'frontend_type' => 'select',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'source_model' => '\Eav\Model\Source\Gender',
            'sort_order' => 50,
        ],

        // Contact Information
        [
            'attribute_code' => 'phone',
            'attribute_label' => 'Phone Number',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 20,
            ],
            'sort_order' => 60,
        ],
        [
            'attribute_code' => 'mobile',
            'attribute_label' => 'Mobile Number',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 20,
            ],
            'sort_order' => 70,
        ],

        // Address Information
        [
            'attribute_code' => 'street_address',
            'attribute_label' => 'Street Address',
            'backend_type' => 'text',
            'frontend_type' => 'textarea',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'sort_order' => 80,
        ],
        [
            'attribute_code' => 'city',
            'attribute_label' => 'City',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 100,
            ],
            'sort_order' => 90,
        ],
        [
            'attribute_code' => 'state',
            'attribute_label' => 'State/Province',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 100,
            ],
            'sort_order' => 100,
        ],
        [
            'attribute_code' => 'postal_code',
            'attribute_label' => 'Postal Code',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 20,
            ],
            'sort_order' => 110,
        ],
        [
            'attribute_code' => 'country',
            'attribute_label' => 'Country',
            'backend_type' => 'varchar',
            'frontend_type' => 'select',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'source_model' => '\Eav\Model\Source\Country',
            'sort_order' => 120,
        ],

        // Account Information
        [
            'attribute_code' => 'customer_group',
            'attribute_label' => 'Customer Group',
            'backend_type' => 'int',
            'frontend_type' => 'select',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => 1,
            'source_model' => '\Eav\Model\Source\CustomerGroup',
            'sort_order' => 130,
        ],
        [
            'attribute_code' => 'account_status',
            'attribute_label' => 'Account Status',
            'backend_type' => 'int',
            'frontend_type' => 'select',
            'is_required' => true,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => 1,
            'source_model' => '\Eav\Model\Source\CustomerStatus',
            'sort_order' => 140,
        ],
        [
            'attribute_code' => 'is_subscribed',
            'attribute_label' => 'Newsletter Subscription',
            'backend_type' => 'int',
            'frontend_type' => 'boolean',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => 0,
            'sort_order' => 150,
        ],

        // Business Information
        [
            'attribute_code' => 'company',
            'attribute_label' => 'Company Name',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 255,
            ],
            'sort_order' => 160,
        ],
        [
            'attribute_code' => 'tax_id',
            'attribute_label' => 'Tax ID',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 50,
            ],
            'sort_order' => 170,
        ],

        // Additional
        [
            'attribute_code' => 'notes',
            'attribute_label' => 'Customer Notes',
            'backend_type' => 'text',
            'frontend_type' => 'textarea',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'sort_order' => 180,
        ],
    ],
];
