<?php
/** @var \Core\Utils\Url $url */
$url = $this->getDI()->get('url');
?><!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= htmlspecialchars($title ?? 'Our Framework') ?></title>
    <link rel="stylesheet" href="<?= $url->get('css/bootstrap.min.css', [], true) ?>">
    <link rel="stylesheet" href="<?= $url->get('css/bootstrap-icons.min.css', [], true) ?>">
    <link rel="stylesheet" href="<?= $url->get('css/kit-enterprise.css', [], true) ?>">
    <link rel="stylesheet" href="<?= $url->get('css/app.css', [], true) ?>">
    <?=$this->yield('html-header')?>
</head>
<body>
    <div class="enterprise-layout">
        <div class="enterprise-login__body">
            <?=$this->yield('content')?>
        </div>
    </div>
    <script src="<?= $url->get('js/bootstrap.bundle.min.js') ?>"></script>
    <script src="<?= $url->get('js/kit-enterprise.js') ?>"></script>
    <script src="<?= $url->get('js/app.js') ?>"></script>
    <?=$this->yield('html-footer')?>
</body>
</html>