<?php
/** @var \Core\Utils\Url $url */
$url = $this->getDI()->get('url');
?><!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= htmlspecialchars($title ?? 'Our Framework') ?></title>
    <link rel="stylesheet" href="<?= $url->get('css/bootstrap.min.css', [], true) ?>">
    <link rel="stylesheet" href="<?= $url->get('css/bootstrap-icons.min.css', [], true) ?>">
    <link rel="stylesheet" href="<?= $url->get('css/app.css', [], true) ?>">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-auto sticky-top bg-dark">
            <?=$this->partial('layout/ui/sidebar')?>
        </div>
        <div class="col-sm min-vh-100 content">
            <?php echo $this->yield('content'); ?>
        </div>
    </div>
</div>

    <?php if (($messages = $this->messages()) && count($messages) > 0) : ?>
        <div aria-live="polite" aria-atomic="true" class="position-relative">
            <div class="toast-container top-0 end-0 p-3">
                <?php foreach ($messages as $msg) : ?>
                    <div class="toast text-bg-<?= $msg['type'] ?>" role="alert" aria-live="assertive" aria-atomic="true">
                        <div class="d-flex">
                            <div class="toast-body"><?= $msg['message'] ?></div>
                            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>



   
    <script src="<?= $url->get('js/bootstrap.bundle.min.js') ?>"></script>
    <script src="<?= $url->get('js/app.js') ?>"></script>
</body>

</html>