<?php
/** @var \Core\Utils\Url $url */
$url = $this->getDI()->get('url');
?><!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= htmlspecialchars($title ?? 'Our Framework') ?></title>
    <link rel="stylesheet" href="<?= $url->get('css/bootstrap.min.css', [], true) ?>">
    <link rel="stylesheet" href="<?= $url->get('css/bootstrap-icons.min.css', [], true) ?>">
    <link rel="stylesheet" href="<?= $url->get('css/app.css', [], true) ?>">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-auto sticky-top bg-dark">
                <?=$this->partial('layout/ui/sidebar')?>
            </div>
            <div class="col-sm min-vh-100 content">
                <?=$this->partial('layout/ui/usernav')?>
                
                <?=$this->partial('layout/ui/messages')?>
                <?php echo $this->yield('content'); ?>
            </div>
        </div>
    </div>
    <script src="<?= $url->get('js/bootstrap.bundle.min.js') ?>"></script>
    <script src="<?= $url->get('js/app.js') ?>"></script>
</body>
</html>