<div class="form-group">
    <label for="<?= $name ?>" class="col-sm-2 control-label">
        <?= $field['options']['label'] ?>
    </label>
    <div class="col-sm-10">
        <?php
        $value = htmlspecialchars($value);
        $attributes = '';
        
        foreach ($field['options']['attributes'] as $attr => $val) {
            $attributes .= " $attr=\"$val\"";
        }
        
        if ($field['type'] === 'textarea') {
            echo "<textarea name=\"$name\" class=\"form-control\"$attributes>$value</textarea>";
        } else {
            echo "<input type=\"{$field['type']}\" name=\"$name\" value=\"$value\" class=\"form-control\"$attributes>";
        }
        ?>
    </div>
</div>