<?php 

use Core\Utils\Tag;
/** @var \Core\Mvc\View $this */
$url = $this->getDI()->get('url');

/** @var \Intern\Decorator\TaskItem[] $tasks */
?>
<h1>Task List</h1>
<a href="<?= $url->get('admin/task-create') ?>" class="btn btn-primary mb-2">Add New Task</a>



<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#filterCanvas" role="button" aria-controls="filterCanvas">
  Link with href
</a>

<div class="offcanvas offcanvas-start text-bg-dark" tabindex="-1" id="filterCanvas" aria-labelledby="filterCanvasLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="filterCanvasLabel">Task Filter</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <div>
        Some text as placeholder. In real life you can have the elements you have chosen. Like, text, images, lists, etc.
        </div>

        <div>
            <h4>Status</h4>
            <?php foreach ($statuses as $status): ?>
                <?php $class = $status->active ? $status->color : 'outline-' . $status->color ?>
                <a href="<?=$status->url?>" class="btn btn-<?=$class?>"><?=$status->title?></a>
            <?php endforeach; ?>
            <hr>

            <h4>Priority</h4>
            <?php foreach ($priorities as $priority): ?>
                <?php $class = $priority->active ? $priority->color : 'outline-' . $priority->color ?>
                <a href="<?=$priority->url?>" class="btn btn-<?=$class?>"><?=$priority->title?></a>
            <?php endforeach; ?>
        </div>
    </div>
</div>




<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Bezeichnung</th>
            <th>Zugewiesen an</th>
            <th>
                <div class="dropdown">
                    <button class="btn btn-link dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Status
                    </button>
                    <ul class="dropdown-menu">
                        
                    </ul>
                </div>
            </th>
            <th>
                <div class="dropdown">
                    <button class="btn btn-link btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Priority
                    </button>
                    <ul class="dropdown-menu">
                        
                    </ul>
                </div>
            </th>
            <th colspan="2">Enddatum</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($tasks as $task): ?>
            <?php // $task->get('created_at') ?>
            <tr>
                <td><?= $task->get('id') ?></td>
                <td><a href="#"><?= $task->get('title') ?></a></td>
                <td><?= $task->getAssignee() ?></td>
                <td><?= $task->getStatusBadge() ?></td>
                <td><?= $task->getPriorityBadge() ?> </td>
                <td><?= $task->getDatePeriod() ?></td>
                <td>
                    <a href="<?= $url->get('admin/task-edit/' . $task->get('id')) ?>">E</a>
                    <a href="<?= $url->get('admin/task-delete/' . $task->get('id')) ?>" onclick="return confirm('Delete this task?')">X</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>