
<?php
/** @var \Core\Utils\Url $url */
$url = $this->getDI()->get('url');

/** @var \Core\UI\Layout $uiLayout */
$uiLayout = $this->getDI()->get('uiLayout');
?>

<div class="d-flex flex-sm-column flex-row flex-nowrap align-items-center">
    <a href="/new" class="d-block p-3 link-light text-decoration-none" title="">
        <i class="bi-bootstrap fs-1"></i>
    </a>
    <ul class="nav nav-pills nav-flush flex-sm-column flex-row flex-nowrap mb-auto mx-auto text-center justify-content-between w-100 px-3 align-items-center">
        <?php foreach($uiLayout->getNavItems() as $item): ?>
            <li class="nav-item">
                <a href="<?=$item['url'] ?>" class="nav-link py-3 px-3<?php echo ($item['active']) ? ' active' : '' ?>" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="<?=$item['label']?>">
                    <i class="bi bi-<?=$item['icon']?> fs-1"></i>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
    <!--
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-circle h2"></i>
        </a>
        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
            <li>
                <a class="dropdown-item" href="#url">
                    <i class="bi bi-icon me-2"></i>
                    label
                </a>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
        </ul>
    </div> -->
</div>