<?php
/** @var \Core\Utils\Url $url */
$url = $this->getDI()->get('url');
$today = date('Y-m-d');
?>
<form class="row" 
      method="post" 
      action="<?=$url->get('add-task')?>" 
      id="simpleTaskForm"
      data-ajax-form
      data-form-title="Create Task"
      data-reset-on-success="true">
    <div class="col-6">
          <input type="text" name="title" class="enterprise-input" placeholder="This Task must be done by..." required>
    </div>
    <div class="col-2">
        <select class="enterprise-select" name="priority_id" required>
            <option value="">Priority</option>
            <?php foreach ($priorities as $prio): ?>
                <option value="<?=$prio->id?>"><?=$prio->title?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="col">
        <div class="input-group">
            <input type="date" class="enterprise-input" value="<?=$today?>" name="begin_date" id="begin_date" required>
            <span class="input-group-text">-</span>
            <input type="date" class="enterprise-input" min="<?=$today?>" value="<?=$today?>" name="end_date" id="end_date" required>
        </div>
    </div>
    <div class="col-1">
        <input type="submit" class="enterprise-button enterprise-button--primary" value="Save">
    </div>
</form>

