<dialog open>
  <article>
    <header>
    <p>
        <strong>Login</strong>
    </p>
    </header>
    <form method="post">
        <fieldset>
            <label>
                ID
                <input name="id" placeholder="ID" />
            </label>
            <label>
                Password
                <input type="password" name="password" placeholder="Password" />
            </label>
        </fieldset>
        <input type="submit" value="Login"/>
    </form>
  </article>
</dialog>