<?php
// app/Eav/Config/entities/category.php

/**
 * Category Entity Configuration
 * 
 * Creates hierarchical category structures with parent-child relationships,
 * positioning data, and status management.
 */
return [
    'entity_code' => 'category',
    'entity_label' => 'Category',
    'entity_table' => 'eav_category_entity',
    'storage_strategy' => 'eav',
    'enable_cache' => true,
    'cache_ttl' => 7200,

    'attributes' => [
        // Basic Information
        [
            'attribute_code' => 'name',
            'attribute_label' => 'Category Name',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => true,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'min_length' => 2,
                'max_length' => 255,
            ],
            'sort_order' => 10,
        ],
        [
            'attribute_code' => 'url_key',
            'attribute_label' => 'URL Key',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => true,
            'is_unique' => true,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'pattern' => '/^[a-z0-9-]+$/',
                'max_length' => 255,
            ],
            'sort_order' => 20,
        ],
        [
            'attribute_code' => 'description',
            'attribute_label' => 'Description',
            'backend_type' => 'text',
            'frontend_type' => 'textarea',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'sort_order' => 30,
        ],

        // Hierarchy
        [
            'attribute_code' => 'parent_id',
            'attribute_label' => 'Parent Category',
            'backend_type' => 'int',
            'frontend_type' => 'select',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'source_model' => '\Eav\Model\Source\CategoryTree',
            'sort_order' => 40,
        ],
        [
            'attribute_code' => 'path',
            'attribute_label' => 'Category Path',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 255,
            ],
            'sort_order' => 50,
        ],
        [
            'attribute_code' => 'level',
            'attribute_label' => 'Category Level',
            'backend_type' => 'int',
            'frontend_type' => 'number',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => 0,
            'validation_rules' => [
                'min' => 0,
            ],
            'sort_order' => 60,
        ],

        // Position and Ordering
        [
            'attribute_code' => 'position',
            'attribute_label' => 'Position',
            'backend_type' => 'int',
            'frontend_type' => 'number',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => 0,
            'sort_order' => 70,
        ],
        [
            'attribute_code' => 'children_count',
            'attribute_label' => 'Children Count',
            'backend_type' => 'int',
            'frontend_type' => 'number',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => 0,
            'sort_order' => 80,
        ],

        // Status and Visibility
        [
            'attribute_code' => 'is_active',
            'attribute_label' => 'Is Active',
            'backend_type' => 'int',
            'frontend_type' => 'boolean',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => 1,
            'sort_order' => 90,
        ],
        [
            'attribute_code' => 'include_in_menu',
            'attribute_label' => 'Include in Navigation Menu',
            'backend_type' => 'int',
            'frontend_type' => 'boolean',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => 1,
            'sort_order' => 100,
        ],

        // Display Settings
        [
            'attribute_code' => 'display_mode',
            'attribute_label' => 'Display Mode',
            'backend_type' => 'varchar',
            'frontend_type' => 'select',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => 'products',
            'source_model' => '\Eav\Model\Source\CategoryDisplayMode',
            'sort_order' => 110,
        ],
        [
            'attribute_code' => 'thumbnail',
            'attribute_label' => 'Thumbnail Image',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 255,
            ],
            'sort_order' => 120,
        ],
        [
            'attribute_code' => 'image',
            'attribute_label' => 'Category Image',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 255,
            ],
            'sort_order' => 130,
        ],

        // SEO
        [
            'attribute_code' => 'meta_title',
            'attribute_label' => 'Meta Title',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 255,
            ],
            'sort_order' => 140,
        ],
        [
            'attribute_code' => 'meta_keywords',
            'attribute_label' => 'Meta Keywords',
            'backend_type' => 'text',
            'frontend_type' => 'textarea',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'sort_order' => 150,
        ],
        [
            'attribute_code' => 'meta_description',
            'attribute_label' => 'Meta Description',
            'backend_type' => 'text',
            'frontend_type' => 'textarea',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'sort_order' => 160,
        ],

        // Additional
        [
            'attribute_code' => 'custom_layout',
            'attribute_label' => 'Custom Design Layout',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 255,
            ],
            'sort_order' => 170,
        ],
    ],
];
