<?php
// app/Eav/Config/entities/product.php

/**
 * Product Entity Configuration
 * 
 * Defines the product entity structure with various attribute types
 * including text fields, numeric values, selections, and timestamps.
 */
return [
    'entity_code' => 'product',
    'entity_label' => 'Product',
    'entity_table' => 'eav_product_entity',
    'storage_strategy' => 'eav',
    'enable_cache' => true,
    'cache_ttl' => 7200,

    'attributes' => [
        // Basic Information
        [
            'attribute_code' => 'name',
            'attribute_label' => 'Product Name',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => true,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => true,
            'is_comparable' => true,
            'default_value' => null,
            'validation_rules' => [
                'min_length' => 3,
                'max_length' => 255,
            ],
            'sort_order' => 10,
        ],
        [
            'attribute_code' => 'sku',
            'attribute_label' => 'SKU',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => true,
            'is_unique' => true,
            'is_searchable' => true,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'pattern' => '/^[A-Z0-9-]+$/',
                'max_length' => 64,
            ],
            'sort_order' => 20,
        ],
        [
            'attribute_code' => 'description',
            'attribute_label' => 'Description',
            'backend_type' => 'text',
            'frontend_type' => 'textarea',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => false,
            'is_comparable' => true,
            'default_value' => null,
            'sort_order' => 30,
        ],

        // Pricing
        [
            'attribute_code' => 'price',
            'attribute_label' => 'Price',
            'backend_type' => 'decimal',
            'frontend_type' => 'number',
            'is_required' => true,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => true,
            'default_value' => 0.00,
            'validation_rules' => [
                'min' => 0,
            ],
            'sort_order' => 40,
        ],
        [
            'attribute_code' => 'special_price',
            'attribute_label' => 'Special Price',
            'backend_type' => 'decimal',
            'frontend_type' => 'number',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => true,
            'default_value' => null,
            'validation_rules' => [
                'min' => 0,
            ],
            'sort_order' => 50,
        ],
        [
            'attribute_code' => 'cost',
            'attribute_label' => 'Cost',
            'backend_type' => 'decimal',
            'frontend_type' => 'number',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => 0.00,
            'validation_rules' => [
                'min' => 0,
            ],
            'sort_order' => 60,
        ],

        // Inventory
        [
            'attribute_code' => 'quantity',
            'attribute_label' => 'Quantity',
            'backend_type' => 'int',
            'frontend_type' => 'number',
            'is_required' => true,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => 0,
            'validation_rules' => [
                'min' => 0,
            ],
            'sort_order' => 70,
        ],
        [
            'attribute_code' => 'weight',
            'attribute_label' => 'Weight',
            'backend_type' => 'decimal',
            'frontend_type' => 'number',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => true,
            'default_value' => null,
            'sort_order' => 80,
        ],

        // Status and Visibility
        [
            'attribute_code' => 'status',
            'attribute_label' => 'Status',
            'backend_type' => 'int',
            'frontend_type' => 'select',
            'is_required' => true,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => 1,
            'source_model' => '\Eav\Model\Source\ProductStatus',
            'sort_order' => 90,
        ],
        [
            'attribute_code' => 'visibility',
            'attribute_label' => 'Visibility',
            'backend_type' => 'int',
            'frontend_type' => 'select',
            'is_required' => true,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => 4,
            'source_model' => '\Eav\Model\Source\ProductVisibility',
            'sort_order' => 100,
        ],

        // Categories and Classification
        [
            'attribute_code' => 'category_ids',
            'attribute_label' => 'Categories',
            'backend_type' => 'text',
            'frontend_type' => 'multiselect',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => null,
            'source_model' => '\Eav\Model\Source\Category',
            'sort_order' => 110,
        ],
        [
            'attribute_code' => 'manufacturer',
            'attribute_label' => 'Manufacturer',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => true,
            'is_filterable' => true,
            'is_comparable' => true,
            'default_value' => null,
            'sort_order' => 120,
        ],

        // Dates
        [
            'attribute_code' => 'special_from_date',
            'attribute_label' => 'Special Price From',
            'backend_type' => 'datetime',
            'frontend_type' => 'date',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'sort_order' => 130,
        ],
        [
            'attribute_code' => 'special_to_date',
            'attribute_label' => 'Special Price To',
            'backend_type' => 'datetime',
            'frontend_type' => 'date',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'sort_order' => 140,
        ],

        // SEO
        [
            'attribute_code' => 'meta_title',
            'attribute_label' => 'Meta Title',
            'backend_type' => 'varchar',
            'frontend_type' => 'text',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'validation_rules' => [
                'max_length' => 255,
            ],
            'sort_order' => 150,
        ],
        [
            'attribute_code' => 'meta_description',
            'attribute_label' => 'Meta Description',
            'backend_type' => 'text',
            'frontend_type' => 'textarea',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => false,
            'is_comparable' => false,
            'default_value' => null,
            'sort_order' => 160,
        ],

        // Additional
        [
            'attribute_code' => 'is_featured',
            'attribute_label' => 'Is Featured',
            'backend_type' => 'int',
            'frontend_type' => 'boolean',
            'is_required' => false,
            'is_unique' => false,
            'is_searchable' => false,
            'is_filterable' => true,
            'is_comparable' => false,
            'default_value' => 0,
            'sort_order' => 170,
        ],
    ],
];
